### ISSUE TITLE
Pikpak功能无法下载

### ISSUE THREAD

**Issue by Oldming1** [NAStool/nas-tools#3418]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v2.9.0 226b07e
>
> 环境: docker

pikpak测试正常，但是下载文件始终提示网络错误。已测试三台设备均出现问题，100%复现。

![image](https://user-images.githubusercontent.com/86954573/217804909-3f46b521-c5e9-43bf-a39d-ca97688f5d67.png)

  log日志：添加种子文件
```
2023-02-09T11:55:19.182404216Z AttributeError: 'NoneType' object has no attribute 'site'
2023-02-09T11:55:37.443990178Z access_token expire, Unauthenticated, please re-login, please refresh_access_token or login
2023-02-09T11:55:47.493678678Z 2023-02-09 19:55:47,492	WARNING: 【Rmt】f0d66eb16d64156ce63e71e5d35ce7290770487c.torrent 未识别出有效信息！
2023-02-09T11:55:47.505908672Z Traceback (most recent call last):
2023-02-09T11:55:47.505944079Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
2023-02-09T11:55:47.505950125Z     return self.wsgi_app(environ, start_response)
2023-02-09T11:55:47.505954529Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
2023-02-09T11:55:47.505958742Z     response = self.handle_exception(e)
2023-02-09T11:55:47.505963864Z   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
2023-02-09T11:55:47.505969997Z     return original_handler(e)
2023-02-09T11:55:47.505975801Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
2023-02-09T11:55:47.505982155Z     response = self.full_dispatch_request()
2023-02-09T11:55:47.505988085Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
2023-02-09T11:55:47.505993826Z     rv = self.handle_user_exception(e)
2023-02-09T11:55:47.505998021Z   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
2023-02-09T11:55:47.506002316Z     return original_handler(e)
2023-02-09T11:55:47.506006472Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
2023-02-09T11:55:47.506010730Z     rv = self.dispatch_request()
2023-02-09T11:55:47.506014949Z   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
2023-02-09T11:55:47.506019311Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2023-02-09T11:55:47.506023586Z   File "/nas-tools/web/main.py", line 107, in login_check
2023-02-09T11:55:47.506028234Z     return func(*args, **kwargs)
2023-02-09T11:55:47.506032407Z   File "/nas-tools/web/main.py", line 1155, in do
2023-02-09T11:55:47.506049189Z     return WebAction().action(cmd, data)
2023-02-09T11:55:47.506054843Z   File "/nas-tools/web/action.py", line 218, in action
2023-02-09T11:55:47.506061452Z     return func(data)
2023-02-09T11:55:47.506067045Z   File "/nas-tools/web/action.py", line 555, in __download_torrent
2023-02-09T11:55:47.506073663Z     __download(media_info, file_path)
2023-02-09T11:55:47.506080655Z   File "/nas-tools/web/action.py", line 530, in __download
2023-02-09T11:55:47.506089962Z     _media_info.site = "WEB"
2023-02-09T11:55:47.506096530Z AttributeError: 'NoneType' object has no attribute 'site'
```

添加磁力下载时
```
2023-02-09T11:55:47.506096530Z AttributeError: 'NoneType' object has no attribute 'site'
2023-02-09T11:57:54.617129881Z create parent folder failed
2023-02-09T11:57:54.617243853Z 2023-02-09 19:57:54,615	INFO: 【Downloader】添加下载任务：magnet:?xt=urn:btih:8bd5553d53e774f8edb4bb590d4f16ebd7e89144&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce，目录：None，Url：magnet:?xt=urn:btih:8bd5553d53e774f8edb4bb590d4f16ebd7e89144&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
2023-02-09T11:57:54.617271169Z 2023-02-09 19:57:54,616	INFO: 【Message】发送消息 telegram：title=添加下载任务失败：磁力链接 , text=站点：WEB
2023-02-09T11:57:54.617277333Z 种子名称：magnet:?xt=urn:btih:8bd5553d53e774f8edb4bb590d4f16ebd7e89144&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
2023-02-09T11:57:54.617284187Z 种子链接：magnet:?xt=urn:btih:8bd5553d53e774f8edb4bb590d4f16ebd7e89144&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
2023-02-09T11:57:54.617290262Z 错误信息：请检查下载任务是否已存在
2023-02-09T11:57:58.746350989Z access_token expire, Unauthenticated, please re-login, please refresh_access_token or login
```

**Comment by jxxghp** [comment]
没有环境，要等PR作者来看了
