### ISSUE TITLE
搜索任何资源都显示为空

### ISSUE THREAD

**Issue by onlyJinx** [NAStool/nas-tools#3491]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.2
>
> 环境: debian11

python版本: Python 3.11.1
使用方式为直接clone代码后使用，`python3 run.py` 方式直接运行；
本地网络到站点是正常的，nastool可以统计到站点的做种数量和上传下载。
请问是python本版不兼容吗？
具体报错如下：
```
root@jellyfin2:~/nas-tools# python3 run.py
正在加载配置：/root/nas-tools/config/config.yaml
NAStool 当前版本号：v2.9.2
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
数据初始化完成
日志输出类型为：console
WEB管理页面用户：admin
未启用https，请使用 http://IP:3000 访问管理页面
TMDB匹配模式：正常模式
媒体管理软件设置为：jellyfin
未配置电影媒体库目录
未配置电视剧媒体库目录
下载软件设置为：qbittorrent
默认文件转移模式为：硬链接
索引器设置为：builtin
微信等移动端渠道搜索已开启自动择优下载
下载软件监控未开启，下载器监控功能已关闭
开始启动服务...
2023-02-13 04:55:25,849 INFO: 站点自动签到服务启动
2023-02-13 04:55:26,376 INFO: RSS订阅服务启动
2023-02-13 04:55:26,378 INFO: 订阅定时搜索服务启动
2023-02-13 04:55:26,378 INFO: 媒体库同步服务启动
Pending jobs:
    SiteSignin.signin (trigger: cron[hour='8', minute='1'], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    SiteUserInfo.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-02-13 04:56:26 CST)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-02-13 04:55:26 CST)
Run time of job "SiteUserInfo.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-02-13 04:56:26 CST)" was missed by 1:59:00.008599
 * Serving Flask app 'web.main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2023-02-13 12:55:57,479 INFO: 【Douban】正在通过API查询豆瓣详情：30167997
2023-02-13 12:55:57,719 INFO: 【Douban】查询到数据：黑豹2
2023-02-13 12:55:58,454 INFO: 【Meta】Black Panther: Wakanda Forever 识别到 电影：TMDBID=505642, 名称=黑豹2, 上映日期=2022-11-09
2023-02-13 12:55:58,455 INFO: 【Meta】正在查询TMDB电影：505642 ...
2023-02-13 12:56:02,753 INFO: 【Meta】正在查询TMDB电影：505642 ...
2023-02-13 12:56:02,764 INFO: 【Web】从TMDB中匹配到电影：黑豹2 (2022)
2023-02-13 12:56:02,764 INFO: 【Web】开始检索 黑豹2 ...
2023-02-13 12:56:02,771 INFO: 【Indexer】开始并行检索 Black Panther: Wakanda Forever，线程数：3 ...
2023-02-13 12:56:02,771 INFO: 【Indexer】开始检索Indexer：观众 ...
2023-02-13 12:56:02,772 INFO: 【Indexer】开始检索Indexer：猫站 ...
2023-02-13 12:56:02,774 INFO: 【Spider】开始请求：https://audiences.me/torrents.php
2023-02-13 12:56:02,777 INFO: 【Indexer】开始检索Indexer：柠檬 ...
2023-02-13 12:56:02,779 INFO: 【Spider】开始请求：https://pterclub.com/torrents.php
2023-02-13 12:56:02,784 INFO: 【Spider】开始请求：https://lemonhd.org/torrents.php

Exception: global flags not at the start of the expression at position 2
Callstack:
Traceback (most recent call last):
  File "/root/nas-tools/app/indexer/client/_spider.py", line 616, in parse
    html_text = response.extract()
                ^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 330, in extract
    return self.selector.get()
           ^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 322, in selector
    self._cached_selector = Selector(self.text)
                                     ^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 285, in text
    self._cached_text = self._absolute_links(self._cached_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 229, in _absolute_links
    text = re.sub(regex, replace_href, text, flags=re.S)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2


2023-02-13 12:56:04,909 WARNING: 【Spider】错误：global flags not at the start of the expression at position 2

Exception: global flags not at the start of the expression at position 2
Callstack:
Traceback (most recent call last):
  File "/root/nas-tools/app/indexer/client/_spider.py", line 616, in parse
    html_text = response.extract()
                ^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 330, in extract
    return self.selector.get()
           ^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 322, in selector
    self._cached_selector = Selector(self.text)
                                     ^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 285, in text
    self._cached_text = self._absolute_links(self._cached_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 229, in _absolute_links
    text = re.sub(regex, replace_href, text, flags=re.S)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2


2023-02-13 12:56:05,074 WARNING: 【Spider】错误：global flags not at the start of the expression at position 2

Exception: global flags not at the start of the expression at position 2
Callstack:
Traceback (most recent call last):
  File "/root/nas-tools/app/indexer/client/_spider.py", line 616, in parse
    html_text = response.extract()
                ^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 330, in extract
    return self.selector.get()
           ^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 322, in selector
    self._cached_selector = Selector(self.text)
                                     ^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 285, in text
    self._cached_text = self._absolute_links(self._cached_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 229, in _absolute_links
    text = re.sub(regex, replace_href, text, flags=re.S)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2


2023-02-13 12:56:05,458 WARNING: 【Spider】错误：global flags not at the start of the expression at position 2
2023-02-13 12:56:05,774 WARNING: 【Indexer】观众 未检索到数据
2023-02-13 12:56:05,774 WARNING: 【Indexer】猫站 未检索到数据
2023-02-13 12:56:05,780 WARNING: 【Indexer】柠檬 未检索到数据
2023-02-13 12:56:05,780 INFO: 【Indexer】所有站点检索完成，有效资源数：0，总耗时 3 秒
2023-02-13 12:56:05,781 INFO: 【Searcher】Black Panther: Wakanda Forever 未检索到资源,尝试通过 黑豹2 重新检索 ...
2023-02-13 12:56:05,786 INFO: 【Indexer】开始并行检索 黑豹2，线程数：3 ...
2023-02-13 12:56:05,786 INFO: 【Indexer】开始检索Indexer：观众 ...
2023-02-13 12:56:05,788 INFO: 【Indexer】开始检索Indexer：猫站 ...
2023-02-13 12:56:05,789 INFO: 【Indexer】开始检索Indexer：柠檬 ...
2023-02-13 12:56:05,792 INFO: 【Spider】开始请求：https://audiences.me/torrents.php
2023-02-13 12:56:05,792 INFO: 【Spider】开始请求：https://pterclub.com/torrents.php
2023-02-13 12:56:05,796 INFO: 【Spider】开始请求：https://lemonhd.org/torrents.php

Exception: global flags not at the start of the expression at position 2
Callstack:
Traceback (most recent call last):
  File "/root/nas-tools/app/indexer/client/_spider.py", line 616, in parse
    html_text = response.extract()
                ^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 330, in extract
    return self.selector.get()
           ^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 322, in selector
    self._cached_selector = Selector(self.text)
                                     ^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 285, in text
    self._cached_text = self._absolute_links(self._cached_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 229, in _absolute_links
    text = re.sub(regex, replace_href, text, flags=re.S)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2


2023-02-13 12:56:06,657 WARNING: 【Spider】错误：global flags not at the start of the expression at position 2
2023-02-13 12:56:06,792 WARNING: 【Indexer】柠檬 未检索到数据

Exception: global flags not at the start of the expression at position 2
Callstack:
Traceback (most recent call last):
  File "/root/nas-tools/app/indexer/client/_spider.py", line 616, in parse
    html_text = response.extract()
                ^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 330, in extract
    return self.selector.get()
           ^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 322, in selector
    self._cached_selector = Selector(self.text)
                                     ^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 285, in text
    self._cached_text = self._absolute_links(self._cached_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 229, in _absolute_links
    text = re.sub(regex, replace_href, text, flags=re.S)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2


2023-02-13 12:56:06,871 WARNING: 【Spider】错误：global flags not at the start of the expression at position 2

Exception: global flags not at the start of the expression at position 2
Callstack:
Traceback (most recent call last):
  File "/root/nas-tools/app/indexer/client/_spider.py", line 616, in parse
    html_text = response.extract()
                ^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 330, in extract
    return self.selector.get()
           ^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 322, in selector
    self._cached_selector = Selector(self.text)
                                     ^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 285, in text
    self._cached_text = self._absolute_links(self._cached_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/nas-tools/third_party/feapder/feapder/network/response.py", line 229, in _absolute_links
    text = re.sub(regex, replace_href, text, flags=re.S)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 2


2023-02-13 12:56:07,504 WARNING: 【Spider】错误：global flags not at the start of the expression at position 2
2023-02-13 12:56:07,789 WARNING: 【Indexer】观众 未检索到数据
2023-02-13 12:56:07,789 WARNING: 【Indexer】猫站 未检索到数据
2023-02-13 12:56:07,790 INFO: 【Indexer】所有站点检索完成，有效资源数：0，总耗时 2 秒
2023-02-13 12:56:07,814 INFO: 【Web】黑豹2 未检索到任何资源
```

**Comment by lllrrr2** [comment]
看这https://github.com/NAStool/nas-tools/issues/3482

**Comment by onlyJinx** [comment]
> 

我确认了一遍。站点都为启用状态。

![image](https://user-images.githubusercontent.com/21324835/218378980-4c9e73dc-8b0c-484a-a7c8-f484b81b6642.png)

**Comment by jxxghp** [comment]
第三方模块不支持python11，安装python 10 运行

**Comment by onlyJinx** [comment]
OK, 使用python10运行正常，谢谢。
