### ISSUE TITLE
3.0订阅电视剧无法搜索下载

### ISSUE THREAD

**Issue by madswaord** [NAStool/nas-tools#3626]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.0 3cc990a
>
> 环境: docker
>

## 你遇到什么问题了？

> 订阅电影使用没有问题，只有在搜索订阅电视剧的时候出现该问题，后台日志卡在处理事件不动或者变成trigger interval提醒，尝试过删除所有订阅重新抓取新版本之后重新订阅仍然无法解决问题， 刷流 订阅电影等都正常 tmdb访问也正常。

> 如UI BUG请提供截图及配置文件截图
<img width="891" alt="截屏2023-03-01 22 20 48" src="https://user-images.githubusercontent.com/86275875/222167663-dac7a6e0-613a-4704-aba6-cf139f9b404f.png">
<img width="694" alt="截屏2023-03-01 13 50 38" src="https://user-images.githubusercontent.com/86275875/222167915-e40295fb-f3a4-4fe6-a121-0590c39f9bbd.png">

> 其它问题提供后台日志，如为Docker请提供docker的日志
2023-03-01 22:18:44,419 INFO: 【Subscribe】共有 2 个电视剧订阅需要检索
2023-03-01 22:18:49,214 INFO: 【Meta】正在查询TMDB电视剧：100088 ...
2023-03-01 22:18:50,409 INFO: 【Meta】正在查询TMDB电视剧：100088 ...
2023-03-01 22:18:50,410 INFO: 【Downloader】最后生还者 (2023) 第1季 共有 9 集
Job "Subscribe.subscribe_search (trigger: interval[0:05:00], next run at: 2023-03-01 22:23:44 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/subscribe.py", line 602, in subscribe_search
    self.subscribe_search_tv(state=state)
  File "/nas-tools/app/subscribe.py", line 754, in subscribe_search_tv
    exist_flag, library_no_exists, _ = self.downloader.check_exists_medias(
  File "/nas-tools/app/downloader/downloader.py", line 930, in check_exists_medias
    no_exists_episodes = self.mediaserver.get_no_exists_episodes(meta_info,
  File "/nas-tools/app/mediaserver/media_server.py", line 135, in get_no_exists_episodes
    return self.server.get_no_exists_episodes(meta_info,
  File "/nas-tools/app/mediaserver/client/plex.py", line 213, in get_no_exists_episodes
    exists_episodes = [episode['episode_num'] for episode in episodes]
TypeError: 'NoneType' object is not iterable

**Comment by lux032** [comment]
同样的问题
