### ISSUE TITLE
无法升级nastools新版本（WINDOWS）

### ISSUE THREAD

**Issue by ra1nzzz** [NAStool/nas-tools#3721]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  windows v2.9.0
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 在原有Nastools目录下载新版Nastool，无论是3.01还是3.02均不可在原有配置文件的基础下运行。
    运行报错：failed to execute script run due to unhandled excption sqlite3……
    在备份完配置文件并删除原config目录后 可以 正常运行，但是一旦导入原有配置文件重启后还是会重现。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 解决升级问题。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by ra1nzzz** [comment]
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 1964, in _exec_single_context
  File "sqlalchemy\engine\default.py", line 747, in do_execute
sqlite3.OperationalError: no such column: SITE_BRUSH_TASK.LABEL

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 115, in <module>
  File "run.py", line 104, in start_service
  File "web\action.py", line 284, in start_service
  File "app\utils\commons.py", line 21, in _singleton
  File "app\brushtask.py", line 38, in __init__
  File "app\brushtask.py", line 50, in init_config
  File "app\brushtask.py", line 79, in get_brushtask_info
  File "app\helper\db_helper.py", line 1720, in get_brushtasks
  File "sqlalchemy\orm\query.py", line 2697, in all
  File "sqlalchemy\orm\query.py", line 2855, in _iter
  File "sqlalchemy\orm\session.py", line 2229, in execute
  File "sqlalchemy\orm\session.py", line 2124, in _execute_internal
  File "sqlalchemy\orm\context.py", line 253, in orm_execute_statement
  File "sqlalchemy\engine\base.py", line 1414, in execute
  File "sqlalchemy\sql\elements.py", line 485, in _execute_on_connection
  File "sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
  File "sqlalchemy\engine\base.py", line 1842, in _execute_context
  File "sqlalchemy\engine\base.py", line 1983, in _exec_single_context
  File "sqlalchemy\engine\base.py", line 2325, in _handle_dbapi_exception
  File "sqlalchemy\engine\base.py", line 1964, in _exec_single_context
  File "sqlalchemy\engine\default.py", line 747, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: SITE_BRUSH_TASK.LABEL
[SQL: SELECT "SITE_BRUSH_TASK"."ID" AS "SITE_BRUSH_TASK_ID", "SITE_BRUSH_TASK"."NAME" AS "SITE_BRUSH_TASK_NAME", "SITE_BRUSH_TASK"."SITE" AS "SITE_BRUSH_TASK_SITE", "SITE_BRUSH_TASK"."FREELEECH" AS "SITE_BRUSH_TASK_FREELEECH", "SITE_BRUSH_TASK"."RSS_RULE" AS "SITE_BRUSH_TASK_RSS_RULE", "SITE_BRUSH_TASK"."REMOVE_RULE" AS "SITE_BRUSH_TASK_REMOVE_RULE", "SITE_BRUSH_TASK"."SEED_SIZE" AS "SITE_BRUSH_TASK_SEED_SIZE", "SITE_BRUSH_TASK"."INTEVAL" AS "SITE_BRUSH_TASK_INTEVAL", "SITE_BRUSH_TASK"."LABEL" AS "SITE_BRUSH_TASK_LABEL", "SITE_BRUSH_TASK"."DOWNLOADER" AS "SITE_BRUSH_TASK_DOWNLOADER", "SITE_BRUSH_TASK"."TRANSFER" AS "SITE_BRUSH_TASK_TRANSFER", "SITE_BRUSH_TASK"."DOWNLOAD_COUNT" AS "SITE_BRUSH_TASK_DOWNLOAD_COUNT", "SITE_BRUSH_TASK"."REMOVE_COUNT" AS "SITE_BRUSH_TASK_REMOVE_COUNT", "SITE_BRUSH_TASK"."DOWNLOAD_SIZE" AS "SITE_BRUSH_TASK_DOWNLOAD_SIZE", "SITE_BRUSH_TASK"."UPLOAD_SIZE" AS "SITE_BRUSH_TASK_UPLOAD_SIZE", "SITE_BRUSH_TASK"."SENDMESSAGE" AS "SITE_BRUSH_TASK_SENDMESSAGE", "SITE_BRUSH_TASK"."STATE" AS "SITE_BRUSH_TASK_STATE", "SITE_BRUSH_TASK"."LST_MOD_DATE" AS "SITE_BRUSH_TASK_LST_MOD_DATE" 
FROM "SITE_BRUSH_TASK" JOIN "CONFIG_SITE" ON "SITE_BRUSH_TASK"."SITE" = "CONFIG_SITE"."ID" ORDER BY CAST("CONFIG_SITE"."PRI" AS INTEGER) ASC]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by ra1nzzz** [comment]
报错截图：https://i.328888.xyz/2023/03/07/53EjV.png

**Comment by Shurelol** [comment]
![image](https://user-images.githubusercontent.com/16237201/223481440-1602a022-c82d-44ae-ae8b-07959a4002e9.png)

**Comment by ra1nzzz** [comment]
> ![image](https://user-images.githubusercontent.com/16237201/223481440-1602a022-c82d-44ae-ae8b-07959a4002e9.png)

SORRY没有找到。感谢！！！

**Comment by tyxxytab** [comment]
我是直接删除config后重新配置解决的

**Comment by jxxghp** [comment]
windows环境下数据库自动升级搞不定，所以一但涉及表结构变更就用不了旧配置。
建议还是转Docker吧。

**Comment by jxxghp** [comment]
3.1.1最新的附件做了调整，可以再试试是否能自动升级了。

**Comment by ra1nzzz** [comment]
> 3.1.1最新的附件做了调整，可以再试试是否能自动升级了。

已经转Docker了 谢谢
