### ISSUE TITLE
自动删种某个url解析报错

### ISSUE THREAD

**Issue by 2Dou** [NAStool/nas-tools#3942]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker
>

## 你遇到什么问题了？

自动删种报错：

```
nas-tools  | [2023-03-22 09:06:58,060] ERROR in app: Exception on /do [POST]
nas-tools  | Traceback (most recent call last):
nas-tools  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
nas-tools  |     response = self.full_dispatch_request()
nas-tools  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
nas-tools  |     rv = self.handle_user_exception(e)
nas-tools  |   File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
nas-tools  |     return original_handler(e)
nas-tools  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
nas-tools  |     rv = self.dispatch_request()
nas-tools  |   File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
nas-tools  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
nas-tools  |   File "/nas-tools/web/main.py", line 113, in login_check
nas-tools  |     return func(*args, **kwargs)
nas-tools  |   File "/nas-tools/web/main.py", line 1044, in do
nas-tools  |     return WebAction().action(cmd, data)
nas-tools  |   File "/nas-tools/web/action.py", line 229, in action
nas-tools  |     return func(data)
nas-tools  |   File "/nas-tools/web/action.py", line 4303, in __get_remove_torrents
nas-tools  |     flag, torrents = TorrentRemover().get_remove_torrents(taskid=tid)
nas-tools  |   File "/nas-tools/app/torrentremover.py", line 313, in get_remove_torrents
nas-tools  |     torrents = self.downloader.get_remove_torrents(
nas-tools  |   File "/nas-tools/app/downloader/downloader.py", line 566, in get_remove_torrents
nas-tools  |     torrents = _client.get_remove_torrents(config=config)
nas-tools  |   File "/nas-tools/app/downloader/client/qbittorrent.py", line 276, in get_remove_torrents
nas-tools  |     "site": parse.urlparse(torrent.tracker).netloc.split(".")[-2],
```

**Comment by 2Dou** [comment]
问题依然存在，应该是辅种检查，在这个文件大概277行那里，有同样的问题。
