### ISSUE TITLE
下载任务无法正常传递给 qbittorrent v4.2.5 并识别

### ISSUE THREAD

**Issue by sumsethan** [NAStool/nas-tools#3970]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.5
>
> 环境: docker on synology（群晖套件版同样有此问题）
>

## 你遇到什么问题了？

> 刷流时使用添加的远程qbittorrent,版本v4.2.5（因机器CPU为armv7，硬件老旧，能安装的最高版本只有v4.2.5），显示添加下载任务出错：*****错误原因：下载器添加任务失败，种子链接******
但此时通过webui查看qbittorrent，任务已添加，保存路径也传递正确，但无标签等信息。

另一个qbittorrent,版本v4.5.2无此问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能够正常使用v4.2.5版本qbittorrent刷流

## 给出程序界面截图、后台运行日志或配置文件
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/9127385/227144868-1171b313-a332-4560-aeac-a3d55e17946e.png">

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by sumsethan** [comment]
Log：

```
更新程序...
Removing __pycache__/
Removing app/__pycache__/
Removing app/conf/__pycache__/
Removing app/db/__pycache__/
Removing app/downloader/__pycache__/
Removing app/downloader/client/__pycache__/
Removing app/helper/__pycache__/
Removing app/indexer/__pycache__/
Removing app/indexer/client/__pycache__/
Removing app/media/__pycache__/
Removing app/media/doubanapi/__pycache__/
Removing app/media/meta/__pycache__/
Removing app/media/tmdbv3api/__pycache__/
Removing app/media/tmdbv3api/objs/__pycache__/
Removing app/mediaserver/__pycache__/
Removing app/mediaserver/client/__pycache__/
Removing app/message/__pycache__/
Removing app/message/client/__pycache__/
Removing app/plugins/__pycache__/
Removing app/plugins/modules/__pycache__/
Removing app/sites/__pycache__/
Removing app/sites/sitesignin/__pycache__/
Removing app/sites/siteuserinfo/__pycache__/
Removing app/utils/__pycache__/
Removing db_scripts/__pycache__/
Removing db_scripts/versions/__pycache__/
Removing web/__pycache__/
Removing web/backend/__pycache__/
From https://ghproxy.com/https://github.com/NAStool/nas-tools
 * branch            master     -> FETCH_HEAD
HEAD is now at f720bd2 Merge pull request #3941 from NAStool/dev
更新成功...
以PUID=0，PGID=0的身份启动程序...
启动Redis...
2023-03-23T16:11:18: PM2 log: Launching in no daemon mode
2023-03-23T16:11:18: PM2 log: App [NAStool:0] starting in -fork mode-
2023-03-23T16:11:18: PM2 log: App [NAStool:0] online
正在加载配置：/config/config.yaml
NAStool 当前版本号：v3.0.5
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
数据初始化完成
日志输出类型为：file
日志将写入文件：/var/packages/NASTool/target/config/logs
WEB管理页面用户：sumsethan
未启用https，请使用 http://IP:3000 访问管理页面
开始启动服务...
2023-03-23 16:11:23,867 INFO: 站点自动签到服务启动
2023-03-23 16:11:23,908 INFO: 数据统计服务启动
Pending jobs:
    Downloader.transfer (trigger: interval[0:05:00], pending)
2023-03-23 16:11:23,982 INFO: 下载文件转移服务启动
2023-03-23 16:11:23,989 INFO: RSS订阅服务启动
2023-03-23 16:11:23,990 INFO: 订阅定时搜索服务启动
2023-03-23 16:11:23,996 INFO: 豆瓣同步服务启动
2023-03-23 16:11:24,002 INFO: 【Sync】读取到监控目录：/volume2/Media/Download/，转移方式：移动
Pending jobs:
    SiteSignin.signin (trigger: cron[hour='8', minute='1'], pending)
    SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-03-23 16:12:23 CST)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
    DoubanSync.sync (trigger: interval[2:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-03-23 16:11:24 CST)
2023-03-23 16:11:24,010 INFO: /volume2/Media/Download/ 的监控服务启动
Pending jobs:
    BrushTask.check_task_rss (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*/30'], pending)
    BrushTask.remove_tasks_torrents (trigger: interval[0:05:00], pending)
2023-03-23 16:11:24,022 INFO: 刷流服务启动
2023-03-23 16:11:24,039 INFO: 已注册事件：subtitle.download<function ChineseSubFinder.download at 0x7f52a9049a20>
2023-03-23 16:11:24,048 INFO: 已注册事件：customhosts.reload<function CustomHosts.reload at 0x7f52a9058430>
2023-03-23 16:11:24,054 INFO: 已注册事件：transfer.finished<function LibraryRefresh.refresh at 0x7f52a90596c0>
2023-03-23 16:11:24,057 INFO: 已注册事件：media.scrap.start<function LibraryScraper.start_scrap at 0x7f52a9059990>
2023-03-23 16:11:24,059 INFO: 已注册事件：emby.webhook<function MovieLike.favtransfer at 0x7f52a905a050>
2023-03-23 16:11:24,061 INFO: 已注册事件：subtitle.download<function OpenSubtitles.download at 0x7f52a905a5f0>
2023-03-23 16:11:24,065 INFO: 已注册事件：emby.webhook<function SpeedLimiter.emby_action at 0x7f52a905b0a0>
2023-03-23 16:11:24,065 INFO: 已注册事件：jellyfin.webhook<function SpeedLimiter.jellyfin_action at 0x7f52a905b130>
2023-03-23 16:11:24,065 INFO: 已注册事件：plex.webhook<function SpeedLimiter.plex_action at 0x7f52a905b1c0>
2023-03-23 16:11:24,071 INFO: 已注册事件：sourcefile.deleted<function TorrentRemover.deletetorrent at 0x7f52a905bbe0>
2023-03-23 16:11:24,072 INFO: 已注册事件：download.add<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,072 INFO: 已注册事件：download.fail<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,072 INFO: 已注册事件：transfer.finished<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：transfer.fail<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：subtitle.download<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：subscribe.add<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：subscribe.finished<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：message.incoming<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：search.start<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：sourcefile.deleted<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,073 INFO: 已注册事件：libraryfile.deleted<function Webhook.send at 0x7f52a90940d0>
2023-03-23 16:11:24,074 INFO: 加载插件：<class 'app.plugins.modules.speedlimiter.SpeedLimiter'>
2023-03-23 16:11:24,074 INFO: 加载插件：<class 'app.plugins.modules.opensubtitles.OpenSubtitles'>
2023-03-23 16:11:24,074 INFO: 加载插件：<class 'app.plugins.modules.chinesesubfinder.ChineseSubFinder'>
2023-03-23 16:11:24,074 INFO: 加载插件：<class 'app.plugins.modules.webhook.Webhook'>
2023-03-23 16:11:24,074 INFO: 加载插件：<class 'app.plugins.modules.synctimer.SyncTimer'>
2023-03-23 16:11:24,075 INFO: 加载插件：<class 'app.plugins.modules.customreleasegroups.CustomReleaseGroups'>
2023-03-23 16:11:24,076 INFO: 加载插件：<class 'app.plugins.modules.movielike.MovieLike'>
2023-03-23 16:11:24,076 INFO: 加载插件：<class 'app.plugins.modules.libraryrefresh.LibraryRefresh'>
2023-03-23 16:11:24,076 INFO: 加载插件：<class 'app.plugins.modules.torrentremover.TorrentRemover'>
2023-03-23 16:11:24,078 INFO: 加载插件：<class 'app.plugins.modules.libraryscraper.LibraryScraper'>
2023-03-23 16:11:24,078 INFO: 加载插件：<class 'app.plugins.modules.customhosts.CustomHosts'>
2023-03-23 16:11:24,078 INFO: 加载插件：<class 'app.plugins.modules.cloudflarespeedtest.CloudflareSpeedTest'>
2023-03-23 16:11:24,078 INFO: 加载插件：<class 'app.plugins.modules.diskspacesaver.DiskSpaceSaver'>
 * Serving Flask app 'web.main'
 * Debug mode: off
::ffff:172.17.0.1 - - [23/Mar/2023 16:12:20] code 400, message Bad request version ('\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00')
::ffff:172.17.0.1 - - [23/Mar/2023 16:12:20] code 400, message Bad request version ('\x00\x14\x00\x12\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x02\x01\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\x1b\x00\x03\x02\x00\x02\x00+\x00\x07\x06ªª\x03\x04\x03\x03\x00-\x00\x02\x01\x01\x00')
2023-03-23 16:12:24,517 ERROR: 【Sites】站点 CarPT 连接失败，状态码：403
2023-03-23 16:13:03,004 INFO: 【Brush】开始站点 Audiences 的刷流任务：Audiences刷流...
2023-03-23 16:13:04,274 INFO: 【Brush】Audiences RSS获取数据：10
Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Callstack:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 316, in _parse_urlencoded
    form = url_decode_stream(stream, self.charset, errors=self.errors, cls=self.cls)
  File "/usr/lib/python3.10/site-packages/werkzeug/urls.py", line 907, in url_decode_stream
    return cls(decoder)
  File "/usr/lib/python3.10/site-packages/werkzeug/datastructures.py", line 346, in __init__
    for key, value in mapping or ():
  File "/usr/lib/python3.10/site-packages/werkzeug/urls.py", line 913, in _url_decode_impl
    for pair in pair_iter:
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 820, in make_chunk_iter
    first_item = next(_iter, b"")
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 689, in _make_chunk_iter
    item = _read(buffer_size)
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 1000, in read
    return self.on_disconnect()
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 929, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1037, in do
    cmd = request.form.get("cmd")
  File "/usr/lib/python3.10/site-packages/werkzeug/utils.py", line 109, in __get__
    value = self.fget(obj)  # type: ignore
  File "/usr/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 436, in form
    self._load_form_data()
  File "/usr/lib/python3.10/site-packages/flask/wrappers.py", line 112, in _load_form_data
    super()._load_form_data()
  File "/usr/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 274, in _load_form_data
    data = parser.parse(
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 268, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 145, in wrapper
    exhaust()
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 957, in exhaust
    for _ in self._exhaust_chunks(chunk_size):
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 944, in _exhaust_chunks
    chunk = self.read(min(to_read, chunk_size))
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 1000, in read
    return self.on_disconnect()
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 929, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2023-03-23 16:13:14,619 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:13:15,253 INFO: 【Downloader】下载器 TS3400D刷流 添加任务：We Lost Our Human 2023 1080p NF WEB-DL x264 DDP5.1-ADWeb，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130388&downhash=482addca
2023-03-23 16:13:40,336 WARNING: 【Brush】Audiences刷流 添加下载任务出错：We Lost Our Human 2023 1080p NF WEB-DL x264 DDP5.1-ADWeb，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130388&downhash=482addcax1
2023-03-23 16:13:47,155 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:13:48,286 INFO: 【Downloader】下载器 TS3400D刷流 添加任务：Chris Rock Total Blackout The Tamborine Extended Cut 2021 1080p NF WEB-DL x264 DDP5.1-ADWeb，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130386&downhash=8a0705bf
2023-03-23 16:14:13,440 WARNING: 【Brush】Audiences刷流 添加下载任务出错：Chris Rock Total Blackout The Tamborine Extended Cut 2021 1080p NF WEB-DL x264 DDP5.1-ADWeb，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130386&downhash=8a0705bf
2023-03-23 16:14:18,487 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:14:19,640 INFO: 【Downloader】下载器 TS3400D刷流 添加任务：Chris Rock Tamborine 2018 1080p NF WEB-DL x264 DDP5.1-ADWeb，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130385&downhash=abb0e
2023-03-23 16:14:44,862 WARNING: 【Brush】Audiences刷流 添加下载任务出错：Chris Rock Tamborine 2018 1080p NF WEB-DL x264 DDP5.1-ADWeb，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130385&downhash=abb0e2
2023-03-23 16:14:48,463 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:14:49,756 INFO: 【Downloader】下载器 TS3400D刷流 添加任务： Geocentric Crisis 2023 1080p WEB-DL H264 AAC-ADWeb，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130382&downhash=cb27ce88x1
2023-03-23 16:15:15,080 WARNING: 【Brush】Audiences刷流 添加下载任务出错： Geocentric Crisis 2023 1080p WEB-DL H264 AAC-ADWeb，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130382&downhash=cb27ce88x1
2023-03-23 16:15:22,272 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:15:23,406 INFO: 【Downloader】下载器 TS3400D刷流 添加任务： Geocentric Crisis 2023 2160p WEB-DL H265 AAC-ADWeb，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130380&downhash=4ee19280x
2023-03-23 16:15:48,799 WARNING: 【Brush】Audiences刷流 添加下载任务出错： Geocentric Crisis 2023 2160p WEB-DL H265 AAC-ADWeb，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130380&downhash=4ee1928
2023-03-23 16:15:54,023 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:15:55,094 INFO: 【Downloader】下载器 TS3400D刷流 添加任务：Im Westen nichts Neues 2022 2160p UHD Blu-ray DoVi HEVC TrueHD Atmos 7.1，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130379&downhash=6b03
2023-03-23 16:16:21,276 WARNING: 【Brush】Audiences刷流 添加下载任务出错：Im Westen nichts Neues 2022 2160p UHD Blu-ray DoVi HEVC TrueHD Atmos 7.1，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130379&downhash=6b03418
2023-03-23 16:16:25,050 INFO: 处理事件：download.add - [<function Webhook.send at 0x7f52a90940d0>]
2023-03-23 16:16:25,535 INFO: 【Downloader】下载器 TS3400D刷流 添加任务： Geocentric Crisis 2023 1080p WEB-DL H265 AAC-ADWeb，目录：/mnt/Disk2/PT-Streaming/，Url：https://audiences.me/download.php?id=130378&downhash=36dc40e
2023-03-23 16:16:51,345 WARNING: 【Brush】Audiences刷流 添加下载任务出错： Geocentric Crisis 2023 1080p WEB-DL H265 AAC-ADWeb，错误原因：下载器添加任务失败，种子链接：https://audiences.me/download.php?id=130378&downhash=36dc4
2023-03-23 16:16:51,346 INFO: 【Brush】任务 Audiences刷流 本次添加了 0 个下载
Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Callstack:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 316, in _parse_urlencoded
    form = url_decode_stream(stream, self.charset, errors=self.errors, cls=self.cls)
  File "/usr/lib/python3.10/site-packages/werkzeug/urls.py", line 907, in url_decode_stream
    return cls(decoder)
  File "/usr/lib/python3.10/site-packages/werkzeug/datastructures.py", line 346, in __init__
    for key, value in mapping or ():
  File "/usr/lib/python3.10/site-packages/werkzeug/urls.py", line 913, in _url_decode_impl
    for pair in pair_iter:
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 820, in make_chunk_iter
    first_item = next(_iter, b"")
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 689, in _make_chunk_iter
    item = _read(buffer_size)
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 1000, in read
    return self.on_disconnect()
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 929, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1037, in do
    cmd = request.form.get("cmd")
  File "/usr/lib/python3.10/site-packages/werkzeug/utils.py", line 109, in __get__
    value = self.fget(obj)  # type: ignore
  File "/usr/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 436, in form
    self._load_form_data()
  File "/usr/lib/python3.10/site-packages/flask/wrappers.py", line 112, in _load_form_data
    super()._load_form_data()
  File "/usr/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 274, in _load_form_data
    data = parser.parse(
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 268, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/usr/lib/python3.10/site-packages/werkzeug/formparser.py", line 145, in wrapper
    exhaust()
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 957, in exhaust
    for _ in self._exhaust_chunks(chunk_size):
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 944, in _exhaust_chunks
    chunk = self.read(min(to_read, chunk_size))
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 1000, in read
    return self.on_disconnect()
  File "/usr/lib/python3.10/site-packages/werkzeug/wsgi.py", line 929, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by sumsethan** [comment]
nastool里显示不出刷流种子信息
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/9127385/227147554-a6dbebe9-ba03-41ca-9645-41e63d9ccbf1.png">
qbittorrent中已经添加了下载
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/9127385/227147474-e8d9681c-66cb-43cf-b289-1ca4e5fbe7a2.png">

**Comment by jxxghp** [comment]
版本太老，升级QB

**Comment by sumsethan** [comment]
> 版本太老，升级QB

问题就是升级不了了

**Comment by sumsethan** [comment]
那我试试自己编译吧-。-

**Comment by juren8848** [comment]
我的qbit是4.5.2也有这个问题，下载任务传递给qbit以后总是显示错误，订阅下载就没有问题，手动下载和刷流都显示种子错误，是哪里设置不对吗

**Comment by sumsethan** [comment]
自己编译也太麻烦了。。依赖各种无法满足。。最终使用 https://github.com/userdocs/qbittorrent-nox-static 预编译的包含了依赖的包解决了，希望能够帮助到后来人
