### ISSUE TITLE
升级版本至v3.1.0 59003e7失败

### ISSUE THREAD

**Issue by PiscesKirito** [NAStool/nas-tools#4013]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.0.2
>
> 环境: Synology
>

## 你遇到什么问题了？

> 尝试升级版本至v3.1.0 59003e7，NASTOOL崩溃，日志显示安装包超时以及找不到包

## 你期望的结果

> 成功升级

## 给出程序界面截图、后台运行日志或配置文件

```
Requirement already satisfied: pickleshare==0.7.5 in /volume1/@appstore/NASTool/lib/python3.10/site-packages (from -r requirements.bak (line 55)) (0.7.5)
Requirement already satisfied: proces==0.1.2 in /volume1/@appstore/NASTool/lib/python3.10/site-packages (from -r requirements.bak (line 56)) (0.1.2)
Requirement already satisfied: prompt-toolkit==3.0.31 in /volume1/@appstore/NASTool/lib/python3.10/site-packages (from -r requirements.bak (line 57)) (3.0.31)
Collecting psutil==5.9.4
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/6e/c8/784968329c1c67c28cce91991ef9af8a8913aa5a3399a6a8954b1380572f/psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  Downloading psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸          215.0/280.2 kB 1.7 kB/s eta 0:00:38
ERROR: Exception:
Traceback (most recent call last):
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/var/packages/python310/target/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/var/packages/python310/target/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/var/packages/python310/target/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/var/packages/python310/target/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/var/packages/python310/target/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/var/packages/NASTool/target/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
无法安装依赖，开始重试...
Traceback (most recent call last):
  File "/volume1/@appstore/NASTool/nas-tools/run.py", line 32, in <module>
    from web.action import WebAction
  File "/volume1/@appstore/NASTool/nas-tools/web/action.py", line 18, in <module>
    from app.brushtask import BrushTask
  File "/volume1/@appstore/NASTool/nas-tools/app/brushtask.py", line 11, in <module>
    from app.downloader import Downloader
  File "/volume1/@appstore/NASTool/nas-tools/app/downloader/__init__.py", line 1, in <module>
    from .downloader import Downloader
  File "/volume1/@appstore/NASTool/nas-tools/app/downloader/downloader.py", line 9, in <module>
    from app.conf import ModuleConf
  File "/volume1/@appstore/NASTool/nas-tools/app/conf/__init__.py", line 1, in <module>
    from .systemconfig import SystemConfig
  File "/volume1/@appstore/NASTool/nas-tools/app/conf/systemconfig.py", line 3, in <module>
    from app.helper import DictHelper
  File "/volume1/@appstore/NASTool/nas-tools/app/helper/__init__.py", line 1, in <module>
    from .chrome_helper import ChromeHelper, init_chrome
  File "/volume1/@appstore/NASTool/nas-tools/app/helper/chrome_helper.py", line 10, in <module>
    import app.helper.cloudflare_helper as CloudflareHelper
  File "/volume1/@appstore/NASTool/nas-tools/app/helper/cloudflare_helper.py", line 3, in <module>
    from func_timeout import func_timeout, FunctionTimedOut
ModuleNotFoundError: No module named 'func_timeout'
```

**Comment by DDSDerek** [comment]
重新拉镜像
