### ISSUE TITLE
v3.1.3依赖缺失？

### ISSUE THREAD

**Issue by royzheng** [NAStool/nas-tools#4140]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.3
>
> 环境: Debian11, python 3.10
>

## 你遇到什么问题了？

> 原生系统安装nas-tools, 平时都是git pull 拉取代码，然后使用python -m pip install -r requirements.txt更新最新，再sudo systemctl start nas-tools,这次更新最新(commit 8bd03b9f5db054fec533dab2aa664d0f3c30d763 (HEAD -> master, tag: v3.1.3, origin/master, origin/HEAD)) 后，使用此方式无法启动了，具体报错见下

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 日志
Apr 05 10:22:16 CA-KSLE1 python[213620]: 未启用https，请使用 http://IP:3000 访问管理页面
Apr 05 10:22:16 CA-KSLE1 python[213620]: 开始启动服务...
Apr 05 10:22:16 CA-KSLE1 python[213620]: Traceback (most recent call last):
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/run.py", line 115, in <module>
Apr 05 10:22:16 CA-KSLE1 python[213620]:     start_service()
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/run.py", line 104, in start_service
Apr 05 10:22:16 CA-KSLE1 python[213620]:     WebAction.start_service()
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/web/action.py", line 292, in start_service
Apr 05 10:22:16 CA-KSLE1 python[213620]:     Scheduler().run_service()
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/scheduler.py", line 78, in run_service
Apr 05 10:22:16 CA-KSLE1 python[213620]:     self.SCHEDULER.add_job(Rss().rssdownload, 'interval', seconds=pt_check_interval)
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/rss.py", line 32, in __init__
Apr 05 10:22:16 CA-KSLE1 python[213620]:     self.init_config()
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/rss.py", line 36, in init_config
Apr 05 10:22:16 CA-KSLE1 python[213620]:     self.downloader = Downloader()
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/utils/commons.py", line 22, in _singleton
Apr 05 10:22:16 CA-KSLE1 python[213620]:     INSTANCES[cls] = cls(*args, **kwargs)
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/downloader/downloader.py", line 52, in __init__
Apr 05 10:22:16 CA-KSLE1 python[213620]:     self._downloader_schema = SubmoduleHelper.import_submodules(
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/helper/submodule_helper.py", line 17, in import_submodules
Apr 05 10:22:16 CA-KSLE1 python[213620]:     packages = importlib.import_module(package).__path__
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
Apr 05 10:22:16 CA-KSLE1 python[213620]:     return _bootstrap._gcd_import(name[level:], package, level)
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/downloader/client/__init__.py", line 1, in <module>
Apr 05 10:22:16 CA-KSLE1 python[213620]:     from .qbittorrent import Qbittorrent
Apr 05 10:22:16 CA-KSLE1 python[213620]:   File "/var/www/nas-tools/app/downloader/client/qbittorrent.py", line 8, in <module>
Apr 05 10:22:16 CA-KSLE1 python[213620]:     import qbittorrentapi
Apr 05 10:22:16 CA-KSLE1 python[213620]: ModuleNotFoundError: No module named 'qbittorrentapi'
Apr 05 10:22:16 CA-KSLE1 systemd[1]: nas-tools.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 10:22:16 CA-KSLE1 systemd[1]: nas-tools.service: Failed with result 'exit-code'.
Apr 05 10:22:16 CA-KSLE1 systemd[1]: nas-tools.service: Consumed 3.116s CPU time.

**Comment by royzheng** [comment]
已解决 应该在 git submodule update --recursive --remote更新下

建议readme更新下？
