### ISSUE TITLE
搜索资源报错问题

### ISSUE THREAD

**Issue by yjb136698605** [NAStool/nas-tools#4170]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v3.1.3
> 环境: docker or windows or Synology
>docker host Synology DS218+

## 你遇到什么问题了？

> 一般搜索，高级搜索报错，订阅刷新不返回结果，最开始在套件版出现这个问题，后重启未解决，后采用docker版有同样的现象，重新手动配置后，使用一段时间后又出现这个问题，重装后恢复备份后还是报错
在索引器中使用单个站点搜索，还是同样报错

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>已经查询过了，没发现类似的

## 你期望的结果

> 能够正常搜索，订阅

## 给出程序界面截图、后台运行日志或配置文件
报错截图
![image](https://user-images.githubusercontent.com/42826895/230566956-5cc4562e-950e-45cd-a46c-c21af8cf7397.png)

普通搜索日志
2023-04-07 15:50:28,254 INFO: 【Meta】正在查询TMDB电影：76600 ...
2023-04-07 15:50:28,264 INFO: 【Meta】76600 查询结果：阿凡达：水之道
2023-04-07 15:50:28,488 INFO: 【Web】从TMDB中匹配到电影：阿凡达：水之道 (2022)
2023-04-07 15:50:32,332 WARNING: 【Indexer】观众 返回数据：15
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 117, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1020, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 239, in action
    return func(data)
  File "/nas-tools/web/action.py", line 515, in __search
    ret, ret_msg = search_medias_for_web(content=search_word,
  File "/nas-tools/app/filter.py", line 152, in check_rules
    if not re.search(r'%s' % exclude.strip(), title, re.IGNORECASE):
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat"
高级搜索
2023-04-07 15:53:44,607 INFO: 【Web】开始检索 阿凡达 ...
2023-04-07 15:53:44,611 INFO: 处理事件：search.start - []
2023-04-07 15:53:44,629 INFO: 【Indexer】开始并行检索 阿凡达，线程数：1 ...
2023-04-07 15:53:44,631 INFO: 【Indexer】开始检索Indexer：观众 ...
2023-04-07 15:53:44,635 INFO: 【Spider】开始请求：https://audiences.me/torrents.php?xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2023-04-07 15:53:45,871 WARNING: 【Indexer】观众 返回数据：23
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 117, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1020, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 239, in action
    return func(data)
  File "/nas-tools/web/action.py", line 515, in __search
    ret, ret_msg = search_medias_for_web(content=search_word,
  File "/nas-tools/web/backend/search_torrents.py", line 133, in search_medias_for_web
    media_list = Searcher().search_medias(key_word=first_search_name,
  File "/nas-tools/app/searcher.py", line 61, in search_medias
    return self.indexer.search_by_keyword(key_word=key_word,
  File "/nas-tools/app/indexer/indexer.py", line 163, in search_by_keyword
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nas-tools/app/indexer/client/builtin.py", line 164, in search
    return self.filter_search_results(result_array=result_array,
  File "/nas-tools/app/indexer/client/_base.py", line 128, in filter_search_results
    match_flag, res_order, match_msg = self.filter.check_torrent_filter(
  File "/nas-tools/app/filter.py", line 318, in check_torrent_filter
    match_flag, order_seq, rule_name = self.check_rules(meta_info)
  File "/nas-tools/app/filter.py", line 152, in check_rules
    if not re.search(r'%s' % exclude.strip(), title, re.IGNORECASE):
  File "/usr/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
订阅刷新
2023-04-07 15:54:39,974 INFO: 【Subscribe】共有 1 个电视剧订阅需要检索
2023-04-07 15:54:39,979 INFO: 【Meta】正在查询TMDB电视剧：208891 ...
2023-04-07 15:54:41,161 INFO: 【Meta】208891 查询结果：天国大魔境
2023-04-07 15:54:41,177 INFO: 【Meta】正在查询TMDB电视剧：208891 ...
2023-04-07 15:54:41,180 INFO: 【Meta】208891 查询结果：天国大魔境
2023-04-07 15:54:41,180 INFO: 【Downloader】天国大魔境 (2023) 第1季 共有 13 集
2023-04-07 15:54:41,415 INFO: 【Downloader】天国大魔境 (2023) 第1季 缺失 13 集
2023-04-07 15:54:41,415 INFO: 【Subscribe】天国大魔境 (2023) 订阅缺失季集：[{'season': 1, 'episodes': [], 'total_episodes': 13}]
2023-04-07 15:54:41,415 INFO: 【Meta】正在查询TMDB电视剧：208891 ...
2023-04-07 15:54:42,381 INFO: 【Meta】208891 查询结果：Tengoku Daimakyo
2023-04-07 15:54:42,382 INFO: 【Searcher】开始检索 Tengoku Daimakyo ...
2023-04-07 15:54:42,388 INFO: 处理事件：search.start - []
2023-04-07 15:54:42,403 INFO: 【Indexer】开始并行检索 Tengoku Daimakyo，线程数：1 ...
2023-04-07 15:54:42,405 INFO: 【Indexer】开始检索Indexer：观众 ...
2023-04-07 15:54:42,417 INFO: 【Spider】开始请求：https://audiences.me/torrents.php?xxxxxxxxxxxxxxxxxxxxxxxxxx
2023-04-07 15:54:45,667 WARNING: 【Indexer】观众 返回数据：1

**Comment by jxxghp** [comment]
问了下ChatGPT：

这是一个 Python 错误回溯，表示在执行 Flask Web 应用程序时发生了异常。该错误似乎是由一个包含无效语法的正则表达式模式引起的，具体来说是“nothing to repeat”。

在回溯中，错误发生在“/nas-tools/app/filter.py”文件的第152行，其中使用“re.search()”函数编译和执行正则表达式模式。正则表达式模式可能包含重复运算符，例如“*”，“+”或“{m，n}”，这些运算符被应用于空字符串或无效的正则表达式。

检查下设置的过滤规则吧，是不是改了什么。

我程序里捕促下异常

**Comment by yjb136698605** [comment]
> 哦，我确实加了一个排除关键词，其中有*号，我排除了，刚搜了一下，没报错了，非常感谢，非常感谢
