### ISSUE TITLE
开启仿真后，显示chrome not reachable

### ISSUE THREAD

**Issue by happyhaha1** [NAStool/nas-tools#4316]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.1.5 872b923
>
> 环境:docker 容器last版本
> 

## 你遇到什么问题了？
>开启仿真后，网站无法访问。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 查看过之前的issues，之前issues显示PUID以及PGID的问题，我尝试不更改环境变量使用默认的环境变量，但是还是相同的报错。

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
`
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 114, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1023, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 243, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4005, in __test_site
    flag, msg, times = Sites().test_connection(data.get("id"))
  File "/nas-tools/app/sites/sites.py", line 266, in test_connection
    if not chrome.visit(url=site_url, ua=ua, cookie=site_cookie, proxy=site_info.get("proxy")):
  File "/nas-tools/app/helper/chrome_helper.py", line 99, in visit
    if not self.browser:
  File "/nas-tools/app/helper/chrome_helper.py", line 50, in browser
    self._chrome = self.__get_browser()
  File "/nas-tools/app/helper/chrome_helper.py", line 93, in __get_browser
    chrome = ChromeWithPrefs(options=options, driver_executable_path=self._executable_path)
  File "/nas-tools/app/helper/chrome_helper.py", line 211, in __init__
    super().__init__(*args, options=options, **kwargs)
  File "/usr/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:36195
from chrome not reachable`

**Comment by DDSDerek** [comment]
试试看用debian镜像

**Comment by happyhaha1** [comment]
debian 镜像url是多少啊

**Comment by happyhaha1** [comment]
> 试试看用debian镜像

找不到debian的镜像

**Comment by DDSDerek** [comment]
> > 试试看用debian镜像
> 
> 找不到debian的镜像

docker pull nastool/nas-tools:debian

**Comment by happyhaha1** [comment]
的确使用了debian 就可以了
