### ISSUE TITLE
class 'app.plugins.modules.autosub.AutoSub'报错了

### ISSUE THREAD

**Issue by Wuyingman** [NAStool/nas-tools#4320]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.1.5
>
> 环境: docker or Unraid
>

## 你遇到什么问题了？
2023-04-15 23:23:24,629 INFO: 加载插件：<class 'app.plugins.modules.autosub.AutoSub'>
Traceback (most recent call last):
  File "/nas-tools/run.py", line 112, in <module>
    start_service()
  File "/nas-tools/run.py", line 105, in start_service
    start_config_monitor()
  File "/nas-tools/initializer.py", line 292, in start_config_monitor
    _observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 155, in __init__
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 400, in _raise_error
    raise OSError(errno.EMFILE, "inotify instance limit reached")
OSError: [Errno 24] inotify instance limit reached
Error submitting job "SiteUserInfo.refresh_site_data_now (trigger: interval[6:00:00], next run at: 2023-04-15 23:24:23 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
> 描述一下你遇到的问题
这是什么报错了
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
否
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![@XG1Y2ZTGC@2B 16MA50FI](https://user-images.githubusercontent.com/89672551/232234264-4765b238-8e96-48d9-be79-32c778c4784b.png)

**Comment by Wuyingman** [comment]
![image](https://user-images.githubusercontent.com/89672551/232234817-26b54286-5f6d-4f82-b9c6-b65187fe4ae9.png)
解决了！
