### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by wn1018** [NAStool/nas-tools#4450]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 启动不了

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 能启动服务

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
text  error  warn  system  array  login  

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/010-update
cont-init: info: /etc/cont-init.d/010-update exited 0
cont-init: info: running /etc/cont-init.d/020-fixuser
cont-init: info: /etc/cont-init.d/020-fixuser exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun NAStool (no readiness notification)
services-up: info: copying legacy longrun redis (no readiness notification)
s6-rc: info: service legacy-services successfully started
2023-04-21 23:24:14,001 INFO: 日志输出类型为：file
2023-04-21 23:24:14,001 INFO: 日志将写入文件：/config/logs
2023-04-21 23:24:14,002 INFO: WEB管理页面用户：admin
2023-04-21 23:24:14,002 INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2023-04-21 23:24:15,318 INFO: Telegram消息接收服务启动
Traceback (most recent call last):
  File "/nas-tools/run.py", line 117, in <module>
    start_service()
  File "/nas-tools/run.py", line 106, in start_service
    WebAction.start_service()
  File "/nas-tools/web/action.py", line 301, in start_service
    Scheduler().run_service()
  File "/nas-tools/app/scheduler.py", line 54, in run_service
    self.start_job(SiteSignin().signin, "站点自动签到", str(ptsignin_cron))
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/site_signin.py", line 38, in __init__
    self.init_config()
  File "/nas-tools/app/sites/site_signin.py", line 41, in init_config
    self.sites = Sites()
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/sites.py", line 31, in __init__
    self.init_config()
  File "/nas-tools/app/sites/sites.py", line 118, in init_config
    limit_interval=int(site_note.get("limit_interval")) * 60,
ValueError: invalid literal for int() with base 10: ''
cont-init: info: /etc/cont-init.d/010-update: 更新主程序...
cont-init: info: /etc/cont-init.d/010-update: From https://github.com/jxxghp/nas-tools
cont-init: info: /etc/cont-init.d/010-update:  * branch            master     -> FETCH_HEAD
cont-init: info: /etc/cont-init.d/010-update: HEAD is now at 29a76b1 Merge pull request #4443 from NAStool/dev
cont-init: info: /etc/cont-init.d/010-update: 主程序更新成功
cont-init: info: /etc/cont-init.d/020-fixuser: 以PUID=99，PGID=100的身份启动程序...
正在加载配置：/config/config.yaml
NAStool 当前版本号：v3.2.0
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
数据初始化完成
开始启动服务...

**Comment by wn1018** [comment]
text  error  warn  system  array  login  

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/010-update
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running



Exception: invalid literal for int() with base 10: ''
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/media/douban.py", line 34, in init_config
    res = RequestUtils(timeout=5).get_res("https://www.douban.com/")
  File "/nas-tools/app/utils/http_utils.py", line 113, in get_res
    return requests.get(url,
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
  File "/nas-tools/run.py", line 47, in sigal_handler
    WebAction.stop_service()
  File "/nas-tools/web/action.py", line 282, in stop_service
    BrushTask().stop_service()
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/brushtask.py", line 39, in __init__
    self.init_config()
  File "/nas-tools/app/brushtask.py", line 44, in init_config
    self.sites = Sites()
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/sites.py", line 31, in __init__
    self.init_config()
  File "/nas-tools/app/sites/sites.py", line 118, in init_config
    limit_interval=int(site_note.get("limit_interval")) * 60,
ValueError: invalid literal for int() with base 10: ''


cont-init: info: /etc/cont-init.d/010-update: 更新主程序...
cont-init: info: /etc/cont-init.d/010-update: Removing __pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/conf/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/db/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/downloader/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/helper/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/indexer/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/media/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/media/doubanapi/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/media/meta/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/media/tmdbv3api/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/media/tmdbv3api/objs/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/mediaserver/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/message/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/message/client/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/plugins/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/sites/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/sites/sitesignin/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing app/utils/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing scripts/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing scripts/versions/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing web/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: Removing web/backend/__pycache__/
cont-init: info: /etc/cont-init.d/010-update: From https://github.com/jxxghp/nas-tools
cont-init: info: /etc/cont-init.d/010-update:  * branch            master     -> FETCH_HEAD
cont-init: info: /etc/cont-init.d/010-update: HEAD is now at 29a76b1 Merge pull request #4443 from NAStool/dev
cont-init: info: /etc/cont-init.d/010-update: 主程序更新成功
cont-init: info: /etc/cont-init.d/010-update exited 0
cont-init: info: running /etc/cont-init.d/020-fixuser
cont-init: info: /etc/cont-init.d/020-fixuser: 以PUID=99，PGID=100的身份启动程序...
cont-init: info: /etc/cont-init.d/020-fixuser: usermod: no changes
cont-init: info: /etc/cont-init.d/020-fixuser exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun NAStool (no readiness notification)
services-up: info: copying legacy longrun redis (no readiness notification)
s6-rc: info: service legacy-services successfully started
2023-04-22 01:34:21,336 INFO: 日志输出类型为：file
2023-04-22 01:34:21,336 INFO: 日志将写入文件：/config/logs
2023-04-22 01:34:21,337 INFO: WEB管理页面用户：admin
2023-04-22 01:34:21,337 INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2023-04-22 01:34:22,835 INFO: Telegram消息接收服务启动
Traceback (most recent call last):
  File "/nas-tools/run.py", line 117, in <module>
    start_service()
  File "/nas-tools/run.py", line 106, in start_service
正在加载配置：/config/config.yaml
NAStool 当前版本号：v3.2.0
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
开始初始化数据...
数据初始化完成
开始启动服务...
    WebAction.start_service()
  File "/nas-tools/web/action.py", line 301, in start_service
    Scheduler().run_service()
  File "/nas-tools/app/scheduler.py", line 54, in run_service
    self.start_job(SiteSignin().signin, "站点自动签到", str(ptsignin_cron))
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/site_signin.py", line 38, in __init__
    self.init_config()
  File "/nas-tools/app/sites/site_signin.py", line 41, in init_config
    self.sites = Sites()
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/sites.py", line 31, in __init__
    self.init_config()
  File "/nas-tools/app/sites/sites.py", line 118, in init_config
    limit_interval=int(site_note.get("limit_interval")) * 60,
ValueError: invalid literal for int() with base 10: ''

**Comment by jxxghp** [comment]
站点流控设置有问题，重新配置吧

**Comment by tree-white** [comment]
> 站点流控设置有问题，重新配置吧

我从站点内点击更新到 3.2.1 最新版本也出现这个问题了，请问“重新配置”是重头来过吗。。这个配置有点多啊，可否只删除站点配置信息呢，我应该如何操作
