### ISSUE TITLE
无法打开管理WEB

### ISSUE THREAD

**Issue by lizyco** [NAStool/nas-tools#4465]
## 你使用的 NAStool 是什么版本，什么环境？

NAStool 当前版本号：v3.2.0
>
> 环境: docker

## 你遇到什么问题了？
更新镜像后，就无法打开网页

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

已经查看过之前的issues，没有得到解决

## 给出程序界面截图、后台运行日志或配置文件
2023-04-22 17:09:57,558 INFO: 日志输出类型为：console
2023-04-22 17:09:57,558 INFO: WEB管理页面用户：admin
2023-04-22 17:09:57,558 INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2023-04-22 17:09:58,857 INFO: 站点自动签到服务启动
2023-04-22 17:09:58,875 INFO: 数据统计服务启动
2023-04-22 17:09:59,016 INFO: 【Config】已加载二级分类策略 default-category
Traceback (most recent call last):
正在加载配置：/config/config.yaml
NAStool 当前版本号：v3.2.0
  File "/nas-tools/run.py", line 117, in <module>
开始初始化数据库...
数据库初始化完成
    start_service()
  File "/nas-tools/run.py", line 106, in start_service
开始更新数据库...
数据库更新完成
    WebAction.start_service()
  File "/nas-tools/web/action.py", line 301, in start_service
开始初始化数据...
数据初始化完成
    Scheduler().run_service()
  File "/nas-tools/app/scheduler.py", line 77, in run_service
    self.SCHEDULER.add_job(Rss().rssdownload, 'interval', seconds=pt_check_interval)
开始启动服务...
  File "/nas-tools/app/rss.py", line 32, in __init__
    self.init_config()
  File "/nas-tools/app/rss.py", line 36, in init_config
    self.downloader = Downloader()
  File "/nas-tools/app/utils/commons.py", line 22, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/downloader/downloader.py", line 58, in __init__
    self.init_config()
  File "/nas-tools/app/downloader/downloader.py", line 64, in init_config
    self.filetransfer = FileTransfer()
  File "/nas-tools/app/filetransfer.py", line 65, in __init__
    self.init_config()
  File "/nas-tools/app/filetransfer.py", line 119, in init_config
    self._ignored_paths = re.compile(r'%s' % re.sub(r';', r'|', ignored_paths))
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0

**Comment by lizyco** [comment]
自己解决，升级之后，最好把config.yaml先删除，让新容器重新初始化。
