### ISSUE TITLE
电视剧转移nfo文件丢失电影正常

### ISSUE THREAD

**Issue by haig233** [NAStool/nas-tools#4522]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: Debian CasaOS docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

使用Rclone移动来进行目录同步，电影和电视剧本体文件移动全部正常，也按照 https://github.com/NAStool/nas-tools/issues/3979#issuecomment-1482291467 进行了对应的目录映射

![image](https://user-images.githubusercontent.com/25719719/234054926-b32f7d52-de12-4b93-b538-2920b50e53cc.png)
![image](https://user-images.githubusercontent.com/25719719/234055054-2bdec677-de1b-4a64-b33f-64538dd42af8.png)

但是，在同步目录时，电影的nfo能同步进去，电视剧的却不行了

如图

![image](https://user-images.githubusercontent.com/25719719/234055274-69f4bb87-df43-47b0-806b-2a5a2fed5ac8.png)

![image](https://user-images.githubusercontent.com/25719719/234055341-f114eb91-5031-4f36-a816-6e24af4e74f0.png)

![image](https://user-images.githubusercontent.com/25719719/234055393-25db334e-be6b-48ef-b83b-dd2bf54bb5ab.png)

电影正常，电视剧的nfo文件丢失

亲测挂载也没有任何问题，正常系统内cp一个随机单文件正常上传

![image](https://user-images.githubusercontent.com/25719719/234055689-9fac1325-ba96-4f41-bbbd-9e13a13df104.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是的
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

电视剧也能正常生成并上传nfo，这样我就可以直接交给emby读nfo下载图片即可
## 给出程序界面截图、后台运行日志或配置文件
```
正在加载配置：/config/config.yaml

Exception: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO "INDEXER_STATISTICS" ("INDEXER", "TYPE", "SECONDS", "RESULT", "DATE") VALUES (?, ?, ?, ?, ?)]
[parameters: ('pthome', 'builtin', 2, 'Y', '2023-04-24 23:55:59')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Callstack:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas-tools/app/db/main_db.py", line 125, in persist
    self.db.commit()
  File "/nas-tools/app/db/main_db.py", line 104, in commit
    self.session.commit()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1903, in commit
    trans.commit(_to_root=True)
  File "", line 2, in commit
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1218, in commit
    self._prepare_impl()
  File "", line 2, in _prepare_impl
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1193, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4153, in flush
    self._flush(objects)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4289, in _flush
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4250, in _flush
    flush_context.execute()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1188, in _emit_insert_statements
    result = connection.execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 485, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO "INDEXER_STATISTICS" ("INDEXER", "TYPE", "SECONDS", "RESULT", "DATE") VALUES (?, ?, ?, ?, ?)]
[parameters: ('pthome', 'builtin', 2, 'Y', '2023-04-24 23:55:59')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-24 23:56:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-24 23:57:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-24 23:58:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-24 23:59:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:00:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:01:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:02:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:03:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:04:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:05:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:06:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:07:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:08:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:09:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:10:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:11:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:12:34 CST)" skipped: maximum number of running instances reached (1)
Execution of job "Sync.transfer_mon_files (trigger: interval[0:01:00], next run at: 2023-04-25 00:13:34 CST)" skipped: maximum number of running instances reached (1)
```

不知道哪里到哪里是，如果不是的话我重新来吧
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by haig233** [comment]
![image](https://user-images.githubusercontent.com/25719719/234152483-d00663bf-6e3e-4495-afd0-a41b7a943d1d.png)
![image](https://user-images.githubusercontent.com/25719719/234152501-318707d6-b963-4096-a2f0-eeb5aa241db4.png)
![image](https://user-images.githubusercontent.com/25719719/234152532-07b13348-d9c9-4b71-8bba-a339ed1ef704.png)

电影依旧正常，剧集还是丢失的
