### ISSUE TITLE
添加下载任务时提示添加下载失败

### ISSUE THREAD

**Issue by chris5641** [NAStool/nas-tools#4523]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.0
>
> 环境: docker or windows or Synology
> docker

## 你遇到什么问题了？

> 在nastools里面搜索资源后，点击下载，提示添加下载失败 下载设置 预设 所选下载器失效！
 我的Qbittorrent是4.4.5版本，在下载器已经设置完成并测试成功

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

<html>
<body>

00:35:22 | Meta | 正在查询TMDB电影：255756 ...
-- | -- | --
00:35:22 | Meta | 255756 查询结果：白日焰火
00:35:22 | System | 处理事件：download.add - [<function Webhook.send at 0x7f8938f60430>]
00:35:24 | Message | 发送消息 WeChat：title=添加下载任务失败：白日焰火 (2014) , text=站点：备胎 种子名称：Black Coal Thin Ice 2014 BluRay 1080p DTS-HD MA5.1 x265.10bit-BeiTai 种子链接：https://www.beitai.pt/download.php?id=2832错误信息：添加下载任务失败：请检查下载设置所选下载器是否有效且启用
00:35:24 | System | 处理事件：download.fail - [<function Webhook.send at 0x7f8938f60430>]
00:39:08 | Meta | 正在查询TMDB电影：255756 ...
00:39:08 | Meta | 255756 查询结果：白日焰火
00:39:08 | System | 处理事件：download.add - [<function Webhook.send at 0x7f8938f60430>]
00:39:24 | Message | 发送消息 WeChat：title=添加下载任务失败：白日焰火 (2014) , text=站点：猫 种子名称：Black Coal Thin Ice 2014 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD 种子链接：https://pterclub.com/download.php?id=70205&passkey=0be9976701190f7b301eb7936a7c90a2错误信息：添加下载任务失败：请检查下载设置所选下载器是否有效且启用

</body>
</html>

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

`
[2023-04-25 00:35:20,794] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 115, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1044, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 244, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4268, in __get_download_dirs
    dirs = Downloader().get_download_dirs(setting=sid)
  File "/nas-tools/app/downloader/downloader.py", line 1162, in get_download_dirs
    save_path_list = [attr.get("save_path") for attr in downloaddir if attr.get("save_path")]
TypeError: 'NoneType' object is not iterable
2023-04-25 00:35:22,552	INFO: 【Meta】正在查询TMDB电影：255756 ...
2023-04-25 00:35:22,553	INFO: 【Meta】255756 查询结果：白日焰火
2023-04-25 00:35:22,554	DEBUG: 发送事件：download.add - {'media_info': {'id': 255756, 'orgid': 255756, 'title': '白日焰火', 'year': '2014', 'type': '电影', 'media_type': '电影', 'vote': 6.4, 'image': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'imdb_id': 'tt3469910', 'tmdb_id': 255756, 'overview': '外表冷艳的吴志贞（桂纶镁 饰）身上散发着熟女的魅力，这对于男人来说是一种致命的诱惑，对于与她曾有过一面之缘的警察张自力（廖凡 饰）来说更是如此。  \u3000\u3000五年前，吴志贞的丈夫梁志军（王学兵 饰）被警方认定死于一桩离奇碎尸案，当时张自力破案后击毙了持枪拒捕的凶手。五年后，又发生了类似的连环案件，并且这些死者都曾与吴志贞相恋，心结未了的张自力主动接近吴志贞，却飞蛾扑火般的爱上了这个女人，两人遭遇重大生活挫折的人逐渐从惺惺相惜到相爱，随着更加亲密的接触，张自力发现了五年前的真相……', 'link': 'https://www.themoviedb.org/movie/255756', 'season': [], 'episode': [], 'backdrop': 'https://image.tmdb.org/t/p/w500/4elyZUdNoj9GefSYYRrXRyRpSHt.jpg', 'poster': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'org_string': 'Black Coal Thin Ice 2014 BluRay 1080p DTS-HD MA5.1 x265.10bit-BeiTai', 'subtitle': '白日焰火 国语DTS-HDMA5.1/简繁SUP字幕/章节', 'cn_name': None, 'en_name': 'Black Coal Thin Ice', 'total_seasons': 0, 'total_episodes': 0, 'part': None, 'resource_type': 'BluRay', 'resource_effect': None, 'resource_pix': '1080p', 'resource_team': 'BeiTai', 'video_encode': 'X265 10bit', 'audio_encode': 'DTS-HD MA 5.1', 'category': '华语电影', 'douban_id': 0, 'keyword': None, 'original_language': 'zh', 'original_title': '白日焰火', 'release_date': '2014-06-11', 'networks': [], 'runtime': 106, 'fav': '0', 'rss_sites': [], 'search_sites': [], 'site': '备胎', 'site_order': 0, 'user_name': None, 'enclosure': 'https://www.beitai.pt/download.php?id=2832', 'res_order': 0, 'filter_rule': None, 'over_edition': None, 'size': '13.75G', 'seeders': 0, 'peers': 0, 'page_url': 'https://www.beitai.pt/details.php?id=2832&hit=1', 'upload_volume_factor': 1.0, 'download_volume_factor': 1.0, 'hit_and_run': None, 'rssid': None, 'save_path': None, 'download_setting': None, 'ignored_words': [], 'replaced_words': [], 'offset_words': []}, 'is_paused': None, 'tag': None, 'download_dir': None, 'download_setting': '', 'downloader_id': None, 'torrent_file': None}
2023-04-25 00:35:22,554	INFO: 处理事件：download.add - [<function Webhook.send at 0x7f8938f60430>]
2023-04-25 00:35:24,777	DEBUG: 发送事件：download.fail - {'media_info': {'id': 255756, 'orgid': 255756, 'title': '白日焰火', 'year': '2014', 'type': '电影', 'media_type': '电影', 'vote': 6.4, 'image': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'imdb_id': 'tt3469910', 'tmdb_id': 255756, 'overview': '外表冷艳的吴志贞（桂纶镁 饰）身上散发着熟女的魅力，这对于男人来说是一种致命的诱惑，对于与她曾有过一面之缘的警察张自力（廖凡 饰）来说更是如此。  \u3000\u3000五年前，吴志贞的丈夫梁志军（王学兵 饰）被警方认定死于一桩离奇碎尸案，当时张自力破案后击毙了持枪拒捕的凶手。五年后，又发生了类似的连环案件，并且这些死者都曾与吴志贞相恋，心结未了的张自力主动接近吴志贞，却飞蛾扑火般的爱上了这个女人，两人遭遇重大生活挫折的人逐渐从惺惺相惜到相爱，随着更加亲密的接触，张自力发现了五年前的真相……', 'link': 'https://www.themoviedb.org/movie/255756', 'season': [], 'episode': [], 'backdrop': 'https://image.tmdb.org/t/p/w500/4elyZUdNoj9GefSYYRrXRyRpSHt.jpg', 'poster': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'org_string': 'Black Coal Thin Ice 2014 BluRay 1080p DTS-HD MA5.1 x265.10bit-BeiTai', 'subtitle': '白日焰火 国语DTS-HDMA5.1/简繁SUP字幕/章节', 'cn_name': None, 'en_name': 'Black Coal Thin Ice', 'total_seasons': 0, 'total_episodes': 0, 'part': None, 'resource_type': 'BluRay', 'resource_effect': None, 'resource_pix': '1080p', 'resource_team': 'BeiTai', 'video_encode': 'X265 10bit', 'audio_encode': 'DTS-HD MA 5.1', 'category': '华语电影', 'douban_id': 0, 'keyword': None, 'original_language': 'zh', 'original_title': '白日焰火', 'release_date': '2014-06-11', 'networks': [], 'runtime': 106, 'fav': '0', 'rss_sites': [], 'search_sites': [], 'site': '备胎', 'site_order': 0, 'user_name': None, 'enclosure': 'https://www.beitai.pt/download.php?id=2832', 'res_order': 0, 'filter_rule': None, 'over_edition': None, 'size': '13.75G', 'seeders': 0, 'peers': 0, 'page_url': 'https://www.beitai.pt/details.php?id=2832&hit=1', 'upload_volume_factor': 1.0, 'download_volume_factor': 1.0, 'hit_and_run': None, 'rssid': None, 'save_path': None, 'download_setting': None, 'ignored_words': [], 'replaced_words': [], 'offset_words': []}, 'reason': '请检查下载设置所选下载器是否有效且启用'}
2023-04-25 00:35:24,777	INFO: 【Message】发送消息 WeChat：title=添加下载任务失败：白日焰火 (2014) , text=站点：备胎
种子名称：Black Coal Thin Ice 2014 BluRay 1080p DTS-HD MA5.1 x265.10bit-BeiTai
种子链接：https://www.beitai.pt/download.php?id=2832
错误信息：添加下载任务失败：请检查下载设置所选下载器是否有效且启用
2023-04-25 00:35:24,777	INFO: 处理事件：download.fail - [<function Webhook.send at 0x7f8938f60430>]
[2023-04-25 00:38:51,713] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 115, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1044, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 244, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4268, in __get_download_dirs
    dirs = Downloader().get_download_dirs(setting=sid)
  File "/nas-tools/app/downloader/downloader.py", line 1162, in get_download_dirs
    save_path_list = [attr.get("save_path") for attr in downloaddir if attr.get("save_path")]
TypeError: 'NoneType' object is not iterable
[2023-04-25 00:38:53,776] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 115, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1044, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 244, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4268, in __get_download_dirs
    dirs = Downloader().get_download_dirs(setting=sid)
  File "/nas-tools/app/downloader/downloader.py", line 1162, in get_download_dirs
    save_path_list = [attr.get("save_path") for attr in downloaddir if attr.get("save_path")]
TypeError: 'NoneType' object is not iterable
[2023-04-25 00:39:02,646] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 115, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1044, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 244, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4268, in __get_download_dirs
    dirs = Downloader().get_download_dirs(setting=sid)
  File "/nas-tools/app/downloader/downloader.py", line 1162, in get_download_dirs
    save_path_list = [attr.get("save_path") for attr in downloaddir if attr.get("save_path")]
TypeError: 'NoneType' object is not iterable
[2023-04-25 00:39:05,227] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 115, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1044, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 244, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4268, in __get_download_dirs
    dirs = Downloader().get_download_dirs(setting=sid)
  File "/nas-tools/app/downloader/downloader.py", line 1162, in get_download_dirs
    save_path_list = [attr.get("save_path") for attr in downloaddir if attr.get("save_path")]
TypeError: 'NoneType' object is not iterable
[2023-04-25 00:39:07,656] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/nas-tools/web/main.py", line 115, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1044, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 244, in action
    return func(data)
  File "/nas-tools/web/action.py", line 4268, in __get_download_dirs
    dirs = Downloader().get_download_dirs(setting=sid)
  File "/nas-tools/app/downloader/downloader.py", line 1162, in get_download_dirs
    save_path_list = [attr.get("save_path") for attr in downloaddir if attr.get("save_path")]
TypeError: 'NoneType' object is not iterable
2023-04-25 00:39:08,746	INFO: 【Meta】正在查询TMDB电影：255756 ...
2023-04-25 00:39:08,747	INFO: 【Meta】255756 查询结果：白日焰火
2023-04-25 00:39:08,748	DEBUG: 发送事件：download.add - {'media_info': {'id': 255756, 'orgid': 255756, 'title': '白日焰火', 'year': '2014', 'type': '电影', 'media_type': '电影', 'vote': 6.4, 'image': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'imdb_id': 'tt3469910', 'tmdb_id': 255756, 'overview': '外表冷艳的吴志贞（桂纶镁 饰）身上散发着熟女的魅力，这对于男人来说是一种致命的诱惑，对于与她曾有过一面之缘的警察张自力（廖凡 饰）来说更是如此。  \u3000\u3000五年前，吴志贞的丈夫梁志军（王学兵 饰）被警方认定死于一桩离奇碎尸案，当时张自力破案后击毙了持枪拒捕的凶手。五年后，又发生了类似的连环案件，并且这些死者都曾与吴志贞相恋，心结未了的张自力主动接近吴志贞，却飞蛾扑火般的爱上了这个女人，两人遭遇重大生活挫折的人逐渐从惺惺相惜到相爱，随着更加亲密的接触，张自力发现了五年前的真相……', 'link': 'https://www.themoviedb.org/movie/255756', 'season': [], 'episode': [], 'backdrop': 'https://image.tmdb.org/t/p/w500/4elyZUdNoj9GefSYYRrXRyRpSHt.jpg', 'poster': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'org_string': 'Black Coal Thin Ice 2014 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD', 'subtitle': '白日焰火 简繁字幕', 'cn_name': None, 'en_name': 'Black Coal Thin Ice', 'total_seasons': 0, 'total_episodes': 0, 'part': None, 'resource_type': 'BluRay', 'resource_effect': 'REMUX', 'resource_pix': '1080p', 'resource_team': 'LHD', 'video_encode': 'AVC', 'audio_encode': 'DTS-HD MA 5.1', 'category': '华语电影', 'douban_id': 0, 'keyword': None, 'original_language': 'zh', 'original_title': '白日焰火', 'release_date': '2014-06-11', 'networks': [], 'runtime': 106, 'fav': '0', 'rss_sites': [], 'search_sites': [], 'site': '猫', 'site_order': 0, 'user_name': None, 'enclosure': 'https://pterclub.com/download.php?id=70205&passkey=0be9976701190f7b301eb7936a7c90a2', 'res_order': 0, 'filter_rule': None, 'over_edition': None, 'size': '28.68G', 'seeders': 0, 'peers': 0, 'page_url': 'https://pterclub.com/details.php?id=70205', 'upload_volume_factor': 1.0, 'download_volume_factor': 1.0, 'hit_and_run': None, 'rssid': None, 'save_path': None, 'download_setting': None, 'ignored_words': [], 'replaced_words': [], 'offset_words': []}, 'is_paused': None, 'tag': None, 'download_dir': None, 'download_setting': '', 'downloader_id': None, 'torrent_file': None}
2023-04-25 00:39:08,748	INFO: 处理事件：download.add - [<function Webhook.send at 0x7f8938f60430>]
2023-04-25 00:39:24,107	DEBUG: 发送事件：download.fail - {'media_info': {'id': 255756, 'orgid': 255756, 'title': '白日焰火', 'year': '2014', 'type': '电影', 'media_type': '电影', 'vote': 6.4, 'image': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'imdb_id': 'tt3469910', 'tmdb_id': 255756, 'overview': '外表冷艳的吴志贞（桂纶镁 饰）身上散发着熟女的魅力，这对于男人来说是一种致命的诱惑，对于与她曾有过一面之缘的警察张自力（廖凡 饰）来说更是如此。  \u3000\u3000五年前，吴志贞的丈夫梁志军（王学兵 饰）被警方认定死于一桩离奇碎尸案，当时张自力破案后击毙了持枪拒捕的凶手。五年后，又发生了类似的连环案件，并且这些死者都曾与吴志贞相恋，心结未了的张自力主动接近吴志贞，却飞蛾扑火般的爱上了这个女人，两人遭遇重大生活挫折的人逐渐从惺惺相惜到相爱，随着更加亲密的接触，张自力发现了五年前的真相……', 'link': 'https://www.themoviedb.org/movie/255756', 'season': [], 'episode': [], 'backdrop': 'https://image.tmdb.org/t/p/w500/4elyZUdNoj9GefSYYRrXRyRpSHt.jpg', 'poster': 'https://image.tmdb.org/t/p/w500/gRCydXOySeD9ezlPH2ZjKDggh7W.jpg', 'org_string': 'Black Coal Thin Ice 2014 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD', 'subtitle': '白日焰火 简繁字幕', 'cn_name': None, 'en_name': 'Black Coal Thin Ice', 'total_seasons': 0, 'total_episodes': 0, 'part': None, 'resource_type': 'BluRay', 'resource_effect': 'REMUX', 'resource_pix': '1080p', 'resource_team': 'LHD', 'video_encode': 'AVC', 'audio_encode': 'DTS-HD MA 5.1', 'category': '华语电影', 'douban_id': 0, 'keyword': None, 'original_language': 'zh', 'original_title': '白日焰火', 'release_date': '2014-06-11', 'networks': [], 'runtime': 106, 'fav': '0', 'rss_sites': [], 'search_sites': [], 'site': '猫', 'site_order': 0, 'user_name': None, 'enclosure': 'https://pterclub.com/download.php?id=70205&passkey=0be9976701190f7b301eb7936a7c90a2', 'res_order': 0, 'filter_rule': None, 'over_edition': None, 'size': '28.68G', 'seeders': 0, 'peers': 0, 'page_url': 'https://pterclub.com/details.php?id=70205', 'upload_volume_factor': 1.0, 'download_volume_factor': 1.0, 'hit_and_run': None, 'rssid': None, 'save_path': None, 'download_setting': None, 'ignored_words': [], 'replaced_words': [], 'offset_words': []}, 'reason': '请检查下载设置所选下载器是否有效且启用'}
2023-04-25 00:39:24,109	INFO: 【Message】发送消息 WeChat：title=添加下载任务失败：白日焰火 (2014) , text=站点：猫
种子名称：Black Coal Thin Ice 2014 BluRay REMUX 1080p AVC DTS-HD MA 5.1-LHD
种子链接：https://pterclub.com/download.php?id=70205&passkey=0be9976701190f7b301eb7936a7c90a2
错误信息：添加下载任务失败：请检查下载设置所选下载器是否有效且启用
2023-04-25 00:39:24,109	INFO: 处理事件：download.fail - [<function Webhook.send at 0x7f8938f60430>]
`

**Comment by haig233** [comment]
需要手动设置一下默认

**Comment by chris5641** [comment]
> 

设置了默认，依然报错

**Comment by devenhc** [comment]
我这边也是碰到一样的问题了，设置了默认，账号密码，ip端口都正确，但是就是测试失败。

**Comment by lry0829** [comment]
请问最后如何解决的

**Comment by torch132** [comment]
我也有同样的问题

**Comment by torch132** [comment]
突然发现点下载器的右上角，将其设为默认，就解决了
