### ISSUE TITLE
【网络模式不同的问题】bridge模式豆瓣榜单刷不出来host模式搜索功能无法正常使用

### ISSUE THREAD

**Issue by fxqq** [NAStool/nas-tools#4600]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: [v3.2.1 f4efbf2]
>
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 系统unraid，
1、网络模式bridge模式，认证采用的观众站点认证，但豆瓣电影和电视剧榜单刷不出来，只有TMDB榜单可以显示，此模式下可以搜索资源，
2、网络模式改为host模式的话，豆瓣榜单可以正常显示，但是搜索不到资源，查看docker日志显示，
ERROR    | feapder.core.parser_control:deal_request:line:624 | 
                            -------------- TorrentSpider.parse error -------------
                            error          Authentication required.
                            response       None

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
浏览过无同类问题，此问题自3.1.5左右的版本就一直存在，自己反复排查过数次，每次新版本更新都尝试过，重新拉过镜像，删除过配置文件重新配置，一直未能解决，榜单和搜索总有一个不行，bridge模式搜索可以，榜单没有，host模式榜单有，搜索不行。
关于网络环境的说明，unraid的网关设置的是旁路由，旁路由里已经将PT站和PT tracker地址加入不走代理的例外里面，之前发issue反馈过，搜索不行的问题，大佬说检查网络，但是网络是通的，感觉应该也不是CF盾的问题，
搜索过issue列表，近期有一个和我说的现象比较像，也是刷不出豆瓣榜单，https://github.com/NAStool/nas-tools/issues/4545，不过没有详细的截图说明

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

希望bridge模式豆瓣榜单能够刷新出来，或者host模式搜索功能可以正常使用。这个问题困扰我太久了，希望作者能看下什么原因

## 给出程序界面截图、后台运行日志或配置文件
附上订阅搜不到资源的截图如下
<img src="https://img.picgo.net/2023/04/29/host2c7cee3ba59dabe93.png" alt="host2c7cee3ba59dabe93.png" border="0">
> 如UI BUG请提供截图及配置文件截图
豆瓣榜单刷不出来的截图如下
<img src="https://img.picgo.net/2023/04/29/bridgef1e94d9b281a2b74.png" alt="bridgef1e94d9b281a2b74.png" border="0">
> 其它问题提供后台日志，如为Docker请提供docker的日志
相关日志
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2535, in wsgi_app
    return response(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask_sock/__init__.py", line 86, in __call__
    raise ConnectionError()
ConnectionError
2023-04-29 22:53:02,916 INFO: 【Meta】正在查询TMDB电影：640146 ...
2023-04-29 22:53:04,169 INFO: 【Meta】640146 查询结果：蚁人与黄蜂女：量子狂潮
2023-04-29 22:53:04,169 INFO: 【Web】从TMDB中匹配到电影：蚁人与黄蜂女：量子狂潮 (2023)
2023-04-29 22:53:04,170 INFO: 【Web】开始搜索 蚁人与黄蜂女：量子狂潮 ...
2023-04-29 22:53:05,146 INFO: 处理事件：search.start - [<function Webhook.send at 0x150591e29cf0>]
2023-04-29 22:53:05,148 INFO: 【Indexer】开始并行搜索 蚁人与黄蜂女：量子狂潮，线程数：1 ...
2023-04-29 22:53:05,149 INFO: 【Indexer】开始搜索Indexer：观众 ...
2023-04-29 22:53:05,151 INFO: 【Spider】开始请求：https://audiences.me/torrents.php?search_mode=0&page=0&notnewword=1&search=%E8%9A%81%E4%BA%BA%E4%B8%8E%E9%BB%84%E8%9C%82%E5%A5%B3+%E9%87%8F%E5%AD%90%E7%8B%82%E6%BD%AE&401=1
2023-04-29 22:53:05.152 | ERROR    | feapder.core.parser_control:deal_request:line:624 | 
                            -------------- TorrentSpider.parse error -------------
                            error          Authentication required.
                            response       None
                            deal request   <Request https://audiences.me/torrents.php?search_mode=0&page=0&notnewword=1&search=%E8%9A%81%E4%BA%BA%E4%B8%8E%E9%BB%84%E8%9C%82%E5%A5%B3+%E9%87%8F%E5%AD%90%E7%8B%82%E6%BD%AE&401=1>
                            
2023-04-29 22:53:36,188 WARNING: 【Indexer】观众 未搜索到数据
2023-04-29 22:53:36,189 INFO: 【Indexer】所有站点搜索完成，有效资源数：0，总耗时 31 秒
2023-04-29 22:53:36,189 INFO: 【Searcher】蚁人与黄蜂女：量子狂潮 未搜索到资源,尝试通过 Ant-Man and the Wasp: Quantumania 重新搜索 ...
2023-04-29 22:53:36,189 INFO: 处理事件：search.start - [<function Webhook.send at 0x150591e29cf0>]
2023-04-29 22:53:36,191 INFO: 【Indexer】开始并行搜索 Ant-Man and the Wasp: Quantumania，线程数：1 ...
2023-04-29 22:53:36,192 INFO: 【Indexer】开始搜索Indexer：观众 ...
2023-04-29 22:53:36,192 INFO: 【Spider】开始请求：https://audiences.me/torrents.php?search_mode=0&page=0&notnewword=1&search=Ant+Man+and+the+Wasp+Quantumania&401=1
2023-04-29 22:53:36.193 | ERROR    | feapder.core.parser_control:deal_request:line:624 | 
                            -------------- TorrentSpider.parse error -------------
                            error          Authentication required.
                            response       None
                            deal request   <Request https://audiences.me/torrents.php?search_mode=0&page=0&notnewword=1&search=Ant+Man+and+the+Wasp+Quantumania&401=1>

**Comment by jxxghp** [comment]
这是本地网络的问题，你得自己研究下，貌似没办帮你分析

**Comment by fxqq** [comment]
> 这是本地网络的问题，你得自己研究下，貌似没办帮你分析

感谢大佬回复，我自己也反复排查了几次，目前使用最新版本3.2.1和旧版本2.9.1.在birdge模式下都没法正常访问豆瓣榜单，把unraid的网关改为主路由网关后可以刷出豆瓣榜单，但是，当我用host模式的时候，2.9.1可以正常显示豆瓣榜单，可以正常搜索，但3.2.1的话只能正常显示豆瓣榜单，搜索用不了，一搜就报| ERROR | feapder.core.parser_control:deal_request:line:624 |这样的错误，所以现在就很困惑，很想用新版本，但这个问题一直找不到解决办法，
