### ISSUE TITLE
3.2.2版本启动失败

### ISSUE THREAD

**Issue by FLIER001** [NAStool/nas-tools#4699]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v3.2.2
>
> 环境: docker in debian
> 

## 你遇到什么问题了？

> 更新3.2.2版本后，不论是程序自动更新，还是docker重新拉取镜像更新，均无法打开后台，错误日志如下：

```
Exception in thread Thread-7357 (_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/simple_websocket/ws.py", line 157, in _thread
    self.sock.send(self.ws.send(Ping()))
  File "/usr/lib/python3.10/site-packages/wsproto/__init__.py", line 64, in send
    data += self.connection.send(event)
  File "/usr/lib/python3.10/site-packages/wsproto/connection.py", line 107, in send
    raise LocalProtocolError(
wsproto.utilities.LocalProtocolError: Event Ping(payload=b'') cannot be sent in state ConnectionState.LOCAL_CLOSING.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2535, in wsgi_app
    return response(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask_sock/__init__.py", line 86, in __call__
    raise ConnectionError()
ConnectionError
```

**Comment by FLIER001** [comment]
定位问题了，是历史遗留的github代理环境变量：`https://ghproxy.com/https://github.com/jxxghp/nas-tools.git`导致的，删掉这一个环境变量就可以登录了。
